export enum Notification {
    deletedFromTrash = "Удалены из корзины",
    movedToTrash = "Помещены в корзину",
    markedAsRead = "Отмечены как прочитанные",
    markedAsUnread = "Отмечены как непрочитанные",
    categoryAdded = "Разряд добавлен",
    categoryChanged = "Разряд изменен",
    groupAdded = "Группа добавлена",
    groupChanged = "Группа изменена",
    groupDeleted = "Группа удалена",
    rightsChanged = "Права изменены",
    roleDeleted = "Роль удалена",
    userAdded = "Пользователь добавлен",
    userRightsChanged = "Права пользователя изменены",
    userRoleChanged = "Роль пользователя изменена",
    userGroupsChanged = "Группы критериев пользователя изменены",
    prolicenseRemoved = "Пролицензия удалена",
    requestAdded = "Заявка подана",
    subscriptionChanged = "Подписка обновлена"
}